
all: caso1.c caso2.c caso3.c case4.c
	gcc -o caso1 caso1.c -L../lib -lcthread -Wall -lrt
	gcc -o caso2 caso2.c -L../lib -lcthread -Wall -lrt
	gcc -o caso3 caso3.c -L../lib -lcthread -Wall -lrt
	gcc -o caso4 caso4.c -L../lib -lcthread -Wall -lrt
	gcc -o caso5 caso5.c -L../lib -lcthread -Wall -lrt

clean:
	rm -rf caso?
	
caso1: caso1.c
	gcc -o caso1 caso1.c -L../lib -lcthread -Wall -lrt
	
caso2: caso2.c
	gcc -o caso2 caso2.c -L../lib -lcthread -Wall -lrt
	
caso3: caso3.c
	gcc -o caso3 caso3.c -L../lib -lcthread -Wall -lrt

caso4: caso4.c
	gcc -o caso4 caso4.c -L../lib -lcthread -Wall -lrt
	
caso5: caso5.c
	gcc -o caso5 caso5.c -L../lib -lcthread -Wall -lrt

	